<?php require_once 'header.php'; ?>

<div id="terms">
<h1>Terms and Conditions</h1>
<p>The following rules and regulations apply to all users and/or visitors to the Sweet Gwendoline Clothing website, the home page of which is at www.SweetGwendolineClothing.com.  This website is owned and operated by Sweet Gwendoline Clothing, LLC.  The use of this website is governed by the policies, terms and conditions set forth below; please read them carefully.  Your use of and visitation to the Sweet Gwendoline Clothing website, including but not limited to: placement of an order and/or submittal of any purchase order, indicates your acceptance of these terms and conditions.  These terms and conditions shall supersede any previous terms and conditions and/or any subsequent terms and conditions included with any purchase order.  Sweet Gwendoline Clothing LLC reserves the right to make changes to this site and these terms and conditions at any time.</p><br />
<h2>Limited License</h2>
<p>This site is owned and operated by Sweet Gwendoline Clothing LLC.  Unless otherwise specified, all materials appearing on this site, including, but not limited to: software or HTML code, scripts, text, logos, graphics, icons, artwork, photographs,video, audio and images (collectively, “Materials”) as well as the selection, assembly and arrangement thereof, are the sole property of Sweet Gwendoline Clothing LLC and are protected by copyright laws and other U.S. and international laws and treaties.  All Materials are provided by Sweet Gwendoline Clothing LLC as a service to its current and prospective customers and may be used only for personal information, shopping, and product ordering purposes and only if you also retain all copyright and proprietary notices contained on the Materials.  No right, title or interest in our Materials is conveyed to you.  This is a limited license, not a transfer of title to our Materials, and such license is subject to the following restrictions:  (a) you may not copy, reproduce, publish, transmit, distribute, perform, display, post, modify, creative derivative works from, sell, license or otherwise exploit this site or any of its Materials without our prior written permission; (b) you may not access or use the Sweet Gwendoline Clothing website for any competitive or commercial purpose; and (c) you will not permit any copying of our Materials.  Any unauthorized copying, alteration, distribution, transmission, performance, display, or other use of these Materials is prohibited.  Sweet Gwendoline Clothing LLC may revoke this limited license at any time for any or no reason.  All rights not expressly granted are reserved by Sweet Gwendoline Clothing LLC.
</p>

<h2>Trademarks and Copyrights</h2> 
<p>Sweet Gwendoline Clothing LLC and its affiliated companies retain all rights regarding their trademarks, trade names, brand names and trade dress.  These marks, names or trade dress, and all associated logos or images, are registered and/or common law trademarks of Sweet Gwendoline Clothing LLC or its affiliated companies, and are protected by U.S. and international laws and treaties.  No license to the use of such marks, names or trade dress is granted to you under these terms and conditions or by your use of the Heroine Heels website.  Your misuse of the trademarks displayed on the Sweet Gwendoline Clothing website, merchandise, products and property is strictly prohibited.  You are also advised that Sweet Gwendoline Clothing LLC will aggressively enforce its intellectual property rights to the fullest extent of the law, including the seeking of civil remedies and criminal prosecution.
</p>

<h2>Linking</h2> 
<p>Periodically, links may be established from this website to one or more external websites or resources operated by third parties (the “Third Party Sites”).  These links are provided for your convenience only.  In addition, certain Third Party Sites also may provide links to the Sweet Gwendoline Clothing website.  None of such links should be deemed to imply that Sweet Gwendoline Clothing LLC endorses the Third Party Sites or any content therein.  Sweet Gwendoline Clothing LLC does not control and is not responsible or liable for any Third Party Sites or any content, advertising, products, or other materials on or available from such Third Party Sites.  Access to any Third Party Sites is at your own risk and Sweet Gwendoline Clothing LLC will have no liability arising out of or related to such websites and/or their content or for any damages or loss caused or alleged to be caused by or in connection with any purchase, use of or reliance on any such content, goods, or services available on or through any such Third Party Site.</p>

<h2>Limitation of Liability & Disclaimer for Products Sold</h2>
<p>
Sweet Gwendoline Clothing LLC makes no representations or warranties, either express or implied, of any kind with respect to products sold on the Sweet Gwendoline Clothing website.  Except as expressly stated herein, Sweet Gwendoline Clothing LLC expressly disclaims all warranties, express or implied, of any kind with respect to products sold on this site, including but not limited to: merchantability and fitness for a particular purpose.  Sweet Gwendoline Clothing LLC, its employees and affiliates will not be responsible for personal injury, property damage or any other loss, claim or damage arising out of, either in whole or in part, the misuse of any items listed on the Sweet Gwendoline Clothing website. You agree that the sole and exclusive maximum liability to Sweet Gwendoline Clothing LLC arising from any product sold on the Sweet Gwendoline Clothing website shall be the price of the product ordered.  In no event shall Sweet Gwendoline Clothing LLC, its directors, officers, employees, or other representatives be liable for special, indirect, consequential, or punitive damages related to any product sold.</p>

<h2>Limitation of Liability & Disclaimer for the Sweet Gwendoline Clothing Website</h2> 
<p>The Sweet Gwendoline Clothing website and the materials therein are provided as is.  Sweet Gwendoline Clothing LLC makes no representations or warranties, either express or implied, of any kind with respect to the Sweet Gwendoline Clothing website, its operation, content, information, or materials.  Sweet Gwendoline Clothing LLC expressly disclaims all warranties, express or implied, of any kind with respect to the website or its use, including but not limited to merchantability and fitness for a particular purpose.  You agree that Sweet Gwendoline Clothing LLC, its directors, officers, employees or other representatives shall not be liable for damages arising from the operation, content, or use of the Sweet Gwendoline Clothing website.  Your agree that this limitation of liability is comprehensive and applies to all damages of any kind, including but not limited to direct, indirect, compensatory, special, incidental, punitive and consequential damages.</p>

<h2>Typographical Errors</h2>
<p>
In the event a product is listed at an incorrect price or with incorrect information due to typographical error or error in pricing or product information received from our suppliers, Sweet Gwendoline Clothing reserves the right to refuse or cancel any orders placed for product listed with incorrect information.  Sweet Gwendoline Clothing LLC reserves the right to refuse or cancel any such orders whether or not the order has been confirmed and your credit card charged.  If your credit card has already been charged for the purchase and your order is cancelled, Sweet Gwendoline Clothing LLC shall immediately issue a credit to your credit card account in the full amount of said charge.
</p>

<h2>Order Acceptance</h2> 
<p>Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does in constitute confirmation of our offer to sell Sweet Gwendoline Clothing LLC reserves the right at any time after receipt of your order to accept or decline your order for any reason.  Sweet Gwendoline Clothing LLC reserves the right at any time after receipt of your order, without prior notice to you, to supply less than the quantity of any item ordered. We may require additional verification or information before accepting any order.  </p>

<h2>Not Included</h2>
<p>All products sold on the Sweet Gwendoline Clothing website are guaranteed against manufacturer defects for 30 days from the date of the invoice, subject to the following conditions: merchandise must be returned in original, undamaged packaging with an outside carton; merchandise must be returned in new, unworn condition, with no obvious signs of use.  Return shipping charges for defective merchandise will be paid by Sweet Gwendoline Clothing LLC.  Original shipping charges are not refundable.
</p>

</div>

<?php require_once 'footer.php'; ?>

